name: 'Compile and build FW'

on:
  push:
    branches:
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile Dev 
      run: ./fbt
    - name: Upload dev artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware_dev-full.dfu
        path: dist/f7-D/flipper-z-f7-full-local.dfu
    - name: Compile Prod (DEBUG=0, COMPACT=1)
      run: ./fbt COMPACT=1 DEBUG=0 updater_package
    - name: Upload prod artifact (DFU)
      uses: actions/upload-artifact@v2
      with:
        name: firmware_prod-full.dfu
        path: dist/f7-C/flipper-z-f7-full-local.dfu
    - name: Create prod artifact (ZIP)
      run: zip -r firmware_prod-full.zip dist/f7-C/f7-update-local
    - name: Upload prod artifact (ZIP)
      uses: actions/upload-artifact@v2
      with:
        name: firmware_prod-full.zip
        path: firmware_prod-full.zip
